services:
    app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.0'
        environment:
            ES_JAVA_OPTS: '-Xmx4g -Xms4g'
        ports:
            - '9200:9200'
            - '9300:9300'
        volumes:
            - 'elasticsearch-data-vol:/usr/share/elasticsearch/data'
            - './elasticsearch/custom.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
        networks:
            - sail

    #    manticoresearch:
    #        image: 'manticoresearch/manticore:latest'
    #        ports:
    #            - '9306:9306'  # Manticore MySQL protokolü
    #            - '9312:9312'  # Manticore Sphinx protokolü
    #            - '9308:9308'  # Manticore HTTP API protokolü
    #        volumes:
    #            - 'manticore-data-vol:/var/lib/manticore'
    #            - './manticore/manticore.conf:/etc/manticoresearch/manticore.conf'
    #        networks:
    #            - sail
    #        depends_on:
    #            - mysql
    #        healthcheck:
    #            test:
    #                - CMD
    #                - curl
    #                - '-f'
    #                - 'http://manticoresearch:9308'
    #            retries: 3
    #            interval: 30s
    #            timeout: 10s

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mysql-data-vol:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis-vol:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    mysql-data-vol:
        driver: local
    elasticsearch-data-vol:
        driver: local
    sail-redis-vol:
        driver: local
